// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/Cards/Card.vue')['default']
    Cards: typeof import('./src/components/Cards/Cards.vue')['default']
    ElAffix: typeof import('element-plus/es/el-affix')['default']
    ElBacktop: typeof import('element-plus/es/el-backtop')['default']
    ElButton: typeof import('element-plus/es/el-button')['default']
    ElCard: typeof import('element-plus/es/el-card')['default']
    ElContainer: typeof import('element-plus/es/el-container')['default']
    ElDivider: typeof import('element-plus/es/el-divider')['default']
    ElFooter: typeof import('element-plus/es/el-footer')['default']
    ElInput: typeof import('element-plus/es/el-input')['default']
    ElLink: typeof import('element-plus/es/el-link')['default']
    ElMain: typeof import('element-plus/es/el-main')['default']
    ElSwitch: typeof import('element-plus/es/el-switch')['default']
    ElTag: typeof import('element-plus/es/el-tag')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
  }
}

export {}
